menu:
- {name: 'research', url: '/publications'}
- {name: 'teaching', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

social:
- {icon: 'linkedin', link: 'https://linkedin.com/in/astrid-thomsen'}
- {icon: 'envelope', link: 'mailto:aut.si@cbs.dk'}

contacts:
- {name: 'Astrid Ulv Thomsen', title: 'PhD Fellow', department: 'Strategy and Innovation', institution: 'Copenhagen Business School', institution_address: 'Kilevej 14A, 2000 Frederiksberg, Denmark', email: 'aut.si@cbs.dk', image: 'assets/img/contact.jpg'}
